# Run all supported functions to check for obvious errors (e.g. seg faults)

from pyvoqc.voqc import VOQC

c = VOQC("tutorial-files/tof_3_example.qasm")
c.write("out.qasm")
c.count_gates()
c.count_clifford_rzq()
c.total_gate_count()
c.check_well_typed(5)
c.convert_to_rzq()
c.convert_to_ibm()
c.decompose_to_cnot()
c.replace_rzq()
c.optimize_1q_gates()
c.cx_cancellation()
c.optimize_ibm()
c.not_propagation()
c.hadamard_reduction()
c.cancel_single_qubit_gates()
c.cancel_two_qubit_gates()
c.merge_rotations()
c.optimize_nam()
c.make_tenerife()
c.trivial_layout(5)
c.check_layout()
c.check_graph()
c.check_constraints()
c.layout_to_list()
c.list_to_layout([2,0,1,3,4])
c.simple_map()
c.make_lnn(5)
c.make_lnn_ring(5)
c.make_grid(2,3)

# If you get here, then nothing crashed.
print("Basic tests passed.")